services:
  saitynai:
    image: saitynai:v1
    build:
      context: .
      dockerfile: ./DockerfileAPI
  db:
    image: db:v1
    build:
      context: .
      dockerfile: ./DockerfileDB
  frontend:
    image: saitynai-frontend:v1
    build:
      context: ../frontend/Saitynai
      dockerfile: ./Dockerfile

